# Generated by Django 2.2.4 on 2019-08-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=30)),
                ('division_logo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_abbreviation', models.CharField(max_length=3, null=True)),
                ('team_logo', models.URLField(null=True)),
                ('team_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lastever.Division')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='division_leage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lastever.League'),
        ),
    ]
