# Generated by Django 2.2.4 on 2019-08-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_abbreviation',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
