# Generated by Django 2.2.4 on 2019-08-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0002_auto_20190817_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='league-a'),
            preserve_default=False,
        ),
    ]
