# Generated by Django 2.2.4 on 2019-08-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0004_auto_20190817_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
