# Generated by Django 2.2.4 on 2019-08-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0005_news_text'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField()),
                ('yellow_cards', models.PositiveSmallIntegerField()),
                ('red_cards', models.PositiveSmallIntegerField()),
                ('game', models.ManyToManyField(to='lastever.Schedule')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lastever.Player')),
            ],
        ),
    ]
