# Generated by Django 2.2.4 on 2019-08-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0006_auto_20190818_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='game',
        ),
        migrations.AddField(
            model_name='schedule',
            name='statistic',
            field=models.ManyToManyField(to='lastever.Statistic'),
        ),
    ]
