# Generated by Django 2.2.4 on 2019-08-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0007_auto_20190818_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='statistic',
        ),
        migrations.AddField(
            model_name='statistic',
            name='game',
            field=models.ManyToManyField(to='lastever.Schedule'),
        ),
    ]
