# Generated by Django 2.2.4 on 2019-08-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0008_auto_20190818_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='game',
        ),
        migrations.AddField(
            model_name='statistic',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lastever.Schedule'),
            preserve_default=False,
        ),
    ]
