# Generated by Django 2.2.4 on 2019-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastever', '0010_auto_20190818_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
    ]
