name: "Lint"

on:
  push:
  pull_request:
  
permissions:
  contents: write

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

        - name: "Set up Python"
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version: "3.13.2"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Format"
          run: python3 -m ruff format .
          
        - name: "Check"
          run: python3 -m ruff check . --fix
          
        - name: "Auto Commit"
          uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
          with:
            commit_message: 'style fixes by ruff'