name: "Lint"

on:
  push:
  pull_request:
  
permissions:
  contents: write

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2

        - name: "Set up Python"
          uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
          with:
            python-version: "3.13.3"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Format"
          run: python3 -m ruff format .
          
        - name: "Check"
          run: python3 -m ruff check . --fix
          
        - name: "Auto Commit"
          uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
          with:
            commit_message: 'style fixes by ruff'